### ISSUE TITLE
Question about the demo.py (selection function)

### ISSUE THREAD

**Issue by ZOE-CA** [SATE-Lab/ATS#1]
First and foremost, thanks so much for sharing the code! ：）
Your idea and method are amazing.

I have a question about PrioritySelectStrategy  function when I run the demo.

!python demo.py

I got the following error. 
![Screenshot (391)](https://user-images.githubusercontent.com/109688199/180043490-73caff72-db67-499a-94c3-9d809c548fa2.png)

Could you help me in solving this problem?
I want to have access to the final selected subset but I can not run it and get the selected subset by using ATS.
Thank you so much.

**Comment by 853108389** [comment]
This problem is caused by adjusting the code structure. You can solve this problem by downloading the latest code
